version: '3.9'

services:
  sqs:
    image: softwaremill/elasticmq-native:latest
    ports:
      - 9324:9324
      - 9325:9325
    volumes:
      - ./infra/elasticmq/elasticmq.conf:/opt/elasticmq.conf